defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: evaluation
- hardware: example
- graph: multi_scale
- model: transformer # Change from default group
- training: default
- _self_

data:
   resolution: n320

hardware:
   num_gpus_per_node: 1
   paths:
      output: /output
      data: .
      graph: /graph
   files:
      dataset: dataset.zarr
      graph: first_graph_n320.pt

training:
   lr:
      rate: 1e-3
